use_cnt: 70
Tag:
- no: 0
  address: 0
  use: true
  gui_display: true
  name: EMS
  description: EMS
  etc: 
  unit: N.C
  value: false
  value_raw: true
  dt_off: 2023-04-12T17:02:14.4844557+09:00
  dt_on: 2023-04-13T11:02:45.2134331+09:00
- no: 1
  address: 1
  use: true
  gui_display: true
  name: E_RIGHT_DOOR
  description: E_RIGHT_DOOR
  etc: 
  unit: N.C
  value: false
  value_raw: true
  dt_off: 2023-04-13T11:02:24.3004163+09:00
  dt_on: 2023-04-13T11:02:45.2134331+09:00
- no: 2
  address: 2
  use: true
  gui_display: true
  name: ELEC_DOOR_OVERRIDE
  description: ELEC_DOOR_OVERRIDE
  etc: 
  unit: N.O
  value: false
  value_raw: true
  dt_off: 2023-04-12T16:18:06.6462942+09:00
  dt_on: 2023-04-13T11:02:45.2134331+09:00
- no: 3
  address: 3
  use: true
  gui_display: true
  name: GPS_UPS_TRIP
  description: GPS_UPS_TRIP
  etc: 
  unit: N.C
  value: false
  value_raw: true
  dt_off: 2023-04-12T17:02:15.8504546+09:00
  dt_on: 2023-04-13T11:02:45.2423657+09:00
- no: 4
  address: 4
  use: false
  gui_display: false
  name: HDIW_POWER_ON
  description: HDIW_POWER_ON
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2023-04-13T11:02:45.2423657+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 5
  address: 5
  use: false
  gui_display: false
  name: HDIW_REMOTE_MODE
  description: HDIW_REMOTE_MODE
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2023-04-13T11:02:45.2423657+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 6
  address: 6
  use: false
  gui_display: false
  name: HDIW_TOTAL_ALARM
  description: HDIW_TOTAL_ALARM
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2023-04-13T11:02:45.2423657+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 7
  address: 6
  use: false
  gui_display: true
  name: MAIN_UNIT_MIX_TRIP
  description: MAIN_UNIT_MIX_TRIP
  etc: 
  unit: N.C
  value: true
  value_raw: false
  dt_off: 2023-04-13T11:02:45.2423657+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 8
  address: 8
  use: true
  gui_display: true
  name: LEFT_FAN_ALARM
  description: LEFT_FAN_ALARM
  etc: 
  unit: N.C
  value: false
  value_raw: true
  dt_off: 2023-01-17T14:50:11.1041877+09:00
  dt_on: 2023-04-13T11:02:45.2423657+09:00
- no: 9
  address: 9
  use: true
  gui_display: true
  name: RIGHT_FAN_ALARM
  description: RIGHT_FAN_ALARM
  etc: 
  unit: N.C
  value: false
  value_raw: true
  dt_off: 0001-01-01T00:00:00.0000000
  dt_on: 2023-04-13T11:02:45.2423657+09:00
- no: 10
  address: 10
  use: false
  gui_display: false
  name: SUPPLY_A_HEATER_DRAIN_V_V
  description: SUPPLY_A_HEATER_DRAIN_V_V
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2023-04-13T11:02:45.2423657+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 11
  address: 11
  use: false
  gui_display: false
  name: SUPPLY_B_HEATER_DRAIN_V_V
  description: SUPPLY_B_HEATER_DRAIN_V_V
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2023-04-13T11:02:45.2423657+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 12
  address: 12
  use: true
  gui_display: true
  name: Drain_Pump_On_Level
  description: Drain_Pump_On_Level
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2023-04-13T11:02:45.2423657+09:00
  dt_on: 2023-04-12T16:32:13.4831682+09:00
- no: 13
  address: 44
  use: true
  gui_display: true
  name: INTERLOCK_TRIP
  description: INTERLOCK_TRIP
  etc: 
  unit: N.C
  value: true
  value_raw: false
  dt_off: 2023-04-13T11:02:45.2423657+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 14
  address: 14
  use: false
  gui_display: false
  name: SPARE_14
  description: SPARE_14
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2023-04-13T11:02:45.2423657+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 15
  address: 15
  use: false
  gui_display: false
  name: SPARE_15
  description: SPARE_15
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2023-04-13T11:02:45.2423657+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 16
  address: 43
  use: true
  gui_display: true
  name: CIRCULATION_PUMP_L_LEAK
  description: CIRCULATION_PUMP_L_LEAK
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2023-04-13T11:02:45.2423657+09:00
  dt_on: 2023-03-17T20:03:33.5766593+09:00
- no: 17
  address: 45
  use: true
  gui_display: true
  name: CIRCULATION_PUMP_R_LEAK
  description: CIRCULATION_PUMP_R_LEAK
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2023-04-13T11:02:45.2423657+09:00
  dt_on: 2023-03-17T20:03:33.5766593+09:00
- no: 18
  address: 46
  use: true
  gui_display: true
  name: CIRCULATION_PUMP_STROKE_1
  description: CIRCULATION_PUMP_STROKE_1
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2023-04-13T11:02:45.2423657+09:00
  dt_on: 2023-03-17T20:03:33.5766593+09:00
- no: 19
  address: 47
  use: true
  gui_display: true
  name: CIRCULATION_PUMP_STROKE_2
  description: CIRCULATION_PUMP_STROKE_2
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2023-04-13T11:02:45.2423657+09:00
  dt_on: 2023-03-17T20:03:33.5766593+09:00
- no: 20
  address: 16
  use: true
  gui_display: true
  name: TANKA_LEVEL_HH
  description: TANKA_LEVEL_HH
  etc: 
  unit: N.C
  value: false
  value_raw: true
  dt_off: 2023-04-12T16:28:21.1052002+09:00
  dt_on: 2023-04-13T11:02:45.2423657+09:00
- no: 21
  address: 17
  use: true
  gui_display: true
  name: TANKA_OVERFLOW_CHECK
  description: TANKA_OVERFLOW_CHECK
  etc: 
  unit: N.C
  value: false
  value_raw: true
  dt_off: 2023-04-12T16:30:21.1261852+09:00
  dt_on: 2023-04-13T11:02:45.2423657+09:00
- no: 22
  address: 18
  use: true
  gui_display: true
  name: TANKB_LEVEL_HH
  description: TANKB_LEVEL_HH
  etc: 
  unit: N.C
  value: false
  value_raw: true
  dt_off: 2023-04-12T16:29:26.3592223+09:00
  dt_on: 2023-04-13T11:02:45.2423657+09:00
- no: 23
  address: 19
  use: true
  gui_display: true
  name: TANKB_OVERFLOW_CHECK
  description: TANKB_OVERFLOW_CHECK
  etc: 
  unit: N.C
  value: false
  value_raw: true
  dt_off: 2023-04-12T16:30:58.1912423+09:00
  dt_on: 2023-04-13T11:02:45.2423657+09:00
- no: 24
  address: 20
  use: true
  gui_display: true
  name: BOTTOM_VAT_LEAK1
  description: BOTTOM_VAT_LEAK1
  etc: 
  unit: N.C
  value: false
  value_raw: true
  dt_off: 2023-04-12T16:41:22.1060820+09:00
  dt_on: 2023-04-13T11:02:45.2423657+09:00
- no: 25
  address: 21
  use: true
  gui_display: true
  name: Drain_Tank_H
  description: Drain_Tank_H
  etc: 
  unit: N.C
  value: false
  value_raw: true
  dt_off: 2023-04-12T16:37:34.0341174+09:00
  dt_on: 2023-04-13T11:02:45.2423657+09:00
- no: 26
  address: 22
  use: true
  gui_display: true
  name: TANK_VAT_LEAK
  description: TANK_VAT_LEAK
  etc: 
  unit: N.C
  value: false
  value_raw: true
  dt_off: 2023-04-12T16:38:59.8790999+09:00
  dt_on: 2023-04-13T11:02:45.2423657+09:00
- no: 27
  address: 24
  use: true
  gui_display: true
  name: DIKE_LEAK
  description: DIKE_LEAK
  etc: 
  unit: N.C
  value: false
  value_raw: true
  dt_off: 2023-04-12T16:42:07.6641042+09:00
  dt_on: 2023-04-13T11:02:45.2423657+09:00
- no: 28
  address: 28
  use: true
  gui_display: true
  name: C_DOOR_ALARM
  description: C_DOOR_ALARM
  etc: 
  unit: N.C
  value: true
  value_raw: false
  dt_off: 2023-04-13T11:02:45.2423657+09:00
  dt_on: 2023-04-12T16:24:44.7582351+09:00
- no: 29
  address: 29
  use: true
  gui_display: true
  name: EXH_LL
  description: EXH_LL
  etc: 
  unit: N.O
  value: true
  value_raw: true
  dt_off: 2023-04-13T11:02:29.8034038+09:00
  dt_on: 2023-04-13T11:02:45.2423657+09:00
- no: 30
  address: 30
  use: false
  gui_display: false
  name: SPARE_30
  description: SPARE_30
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2023-04-13T11:02:45.2423657+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 31
  address: 31
  use: true
  gui_display: true
  name: MAIN_EQ_TRIP
  description: MAIN_EQ_TRIP
  etc: 
  unit: N.C
  value: true
  value_raw: false
  dt_off: 2023-04-13T11:02:45.2423657+09:00
  dt_on: 2023-01-19T11:30:15.5228866+09:00
- no: 32
  address: 32
  use: true
  gui_display: true
  name: TANKA_LEVEL_H
  description: TANKA_LEVEL_H
  etc: 
  unit: N.O
  value: true
  value_raw: true
  dt_off: 2023-04-12T14:00:27.8082079+09:00
  dt_on: 2023-04-13T11:02:45.2423657+09:00
- no: 33
  address: 33
  use: true
  gui_display: true
  name: TANKA_LEVEL_M
  description: TANKA_LEVEL_M
  etc: 
  unit: N.O
  value: true
  value_raw: true
  dt_off: 2023-04-12T13:59:38.0841858+09:00
  dt_on: 2023-04-13T11:02:45.2423657+09:00
- no: 34
  address: 34
  use: true
  gui_display: true
  name: TANKA_LEVEL_L
  description: TANKA_LEVEL_L
  etc: 
  unit: N.O
  value: true
  value_raw: true
  dt_off: 2023-04-12T10:22:09.1267569+09:00
  dt_on: 2023-04-13T11:02:45.2423657+09:00
- no: 35
  address: 35
  use: true
  gui_display: true
  name: TANKA_LEVEL_LL
  description: TANKA_LEVEL_LL
  etc: 
  unit: N.O
  value: true
  value_raw: true
  dt_off: 2023-04-12T10:21:28.6037622+09:00
  dt_on: 2023-04-13T11:02:45.2423657+09:00
- no: 36
  address: 36
  use: true
  gui_display: true
  name: TANKA_EMPTY_CHECK
  description: TANKA_EMPTY_CHECK
  etc: 
  unit: N.O
  value: true
  value_raw: true
  dt_off: 2023-03-15T14:34:48.3792513+09:00
  dt_on: 2023-04-13T11:02:45.2423657+09:00
- no: 37
  address: 37
  use: true
  gui_display: true
  name: TANKB_LEVEL_H
  description: TANKB_LEVEL_H
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2023-04-13T11:02:45.2423657+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 38
  address: 38
  use: true
  gui_display: true
  name: TANKB_LEVEL_M
  description: TANKB_LEVEL_M
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2023-04-13T11:02:45.2423657+09:00
  dt_on: 2023-01-19T11:30:15.5228866+09:00
- no: 39
  address: 39
  use: true
  gui_display: true
  name: TANKB_LEVEL_L
  description: TANKB_LEVEL_L
  etc: 
  unit: N.O
  value: true
  value_raw: true
  dt_off: 2023-04-12T14:48:08.5461188+09:00
  dt_on: 2023-04-13T11:02:45.2423657+09:00
- no: 40
  address: 40
  use: true
  gui_display: true
  name: TANKB_LEVEL_LL
  description: TANKB_LEVEL_LL
  etc: 
  unit: N.O
  value: true
  value_raw: true
  dt_off: 2023-04-12T14:47:26.7641903+09:00
  dt_on: 2023-04-13T11:02:45.2423657+09:00
- no: 41
  address: 41
  use: true
  gui_display: true
  name: TANKB_EMPTY_CHECK
  description: TANKB_EMPTY_CHECK
  etc: 
  unit: N.O
  value: true
  value_raw: true
  dt_off: 2023-04-12T10:52:51.6075636+09:00
  dt_on: 2023-04-13T11:02:45.2423657+09:00
- no: 42
  address: 42
  use: false
  gui_display: false
  name: SPARE_42
  description: SPARE_42
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2023-04-13T11:02:45.2423657+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 43
  address: 43
  use: false
  gui_display: false
  name: RETURN_DRAIN_V_V
  description: RETURN_DRAIN_V_V
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2023-04-13T11:02:45.2423657+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 44
  address: 44
  use: false
  gui_display: false
  name: SPARE_44
  description: SPARE_44
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2023-04-13T11:02:45.2423657+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 45
  address: 45
  use: false
  gui_display: false
  name: CIRCULATION_PUMP_LEFT_ON
  description: CIRCULATION_PUMP_LEFT_ON
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2023-04-13T11:02:45.2423657+09:00
  dt_on: 2023-03-15T14:34:48.4080567+09:00
- no: 46
  address: 46
  use: false
  gui_display: false
  name: CIRCULATION_PUMP_RIGHT_ON
  description: CIRCULATION_PUMP_RIGHT_ON
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2023-04-13T11:02:45.2423657+09:00
  dt_on: 2023-01-17T14:50:10.7271873+09:00
- no: 47
  address: 47
  use: false
  gui_display: false
  name: CIRCULATION_PUMP_LEAK
  description: CIRCULATION_PUMP_LEAK
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2023-04-13T11:02:45.2423657+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 48
  address: 48
  use: false
  gui_display: false
  name: SUPPLY_A_PUMP_LEAK
  description: SUPPLY_A_PUMP_LEAK
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2023-04-13T11:02:45.2423657+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 49
  address: 49
  use: false
  gui_display: false
  name: SUPPLY_B_PUMP_LEAK
  description: SUPPLY_B_PUMP_LEAK
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2023-04-13T11:02:45.2423657+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 50
  address: 50
  use: false
  gui_display: false
  name: SPARE_50
  description: SPARE_50
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2023-04-13T11:02:45.2423657+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 51
  address: 51
  use: false
  gui_display: false
  name: Gas_Detec_Alarm
  description: Gas_Detec_Alarm
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2023-04-13T11:02:45.2423657+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 52
  address: 52
  use: false
  gui_display: false
  name: Purge_Unit_Alarm
  description: Purge_Unit_Alarm
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2023-04-13T11:02:45.2423657+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 53
  address: 53
  use: false
  gui_display: false
  name: LEAK_FAULT
  description: LEAK_FAULT
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2023-04-13T11:02:45.2423657+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 54
  address: 54
  use: false
  gui_display: false
  name: Purge_Unit_OK
  description: Purge_Unit_OK
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2023-04-13T11:02:45.2423657+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 55
  address: 55
  use: false
  gui_display: false
  name: CM_DRAIN_PUMP_ON_LEVEL
  description: CM_DRAIN_PUMP_ON_LEVEL
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2023-04-13T11:02:45.2423657+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 56
  address: 56
  use: false
  gui_display: false
  name: CM_LEAK
  description: CM_LEAK
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2023-04-13T11:02:45.2423657+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 57
  address: 57
  use: false
  gui_display: false
  name: CM_DIKE_LEAK
  description: CM_DIKE_LEAK
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2023-04-13T11:02:45.2423657+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 58
  address: 58
  use: false
  gui_display: false
  name: CM_VAT_LEAK
  description: CM_VAT_LEAK
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2023-04-13T11:02:45.2423657+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 59
  address: 59
  use: false
  gui_display: false
  name: CM_DRAIN_TANK_H
  description: CM_DRAIN_TANK_H
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2023-04-13T11:02:45.2423657+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 60
  address: 48
  use: true
  gui_display: true
  name: SUPPLY_A_PUMP_L_LEAK
  description: SUPPLY_A_PUMP_L_LEAK
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2023-04-13T11:02:45.2423657+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 61
  address: 49
  use: true
  gui_display: true
  name: SUPPLY_A_PUMP_R_LEAK
  description: SUPPLY_A_PUMP_R_LEAK
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2023-04-13T11:02:45.2423657+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 62
  address: 50
  use: true
  gui_display: true
  name: SUPPLY_A_PUMP_STOKRE_1
  description: SUPPLY_A_PUMP_STOKRE_1
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2023-04-13T11:02:45.2423657+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 63
  address: 51
  use: true
  gui_display: true
  name: SUPPLY_A_PUMP_STOKRE_2
  description: SUPPLY_A_PUMP_STOKRE_2
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2023-04-13T11:02:45.2423657+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 64
  address: 52
  use: true
  gui_display: true
  name: SUPPLY_B_PUMP_L_LEAK
  description: SUPPLY_B_PUMP_L_LEAK
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2023-04-13T11:02:45.2423657+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 65
  address: 53
  use: true
  gui_display: true
  name: SUPPLY_A_PUMP_R_LEAK
  description: SUPPLY_A_PUMP_R_LEAK
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2023-04-13T11:02:45.2713639+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 66
  address: 54
  use: true
  gui_display: true
  name: SUPPLY_B_PUMP_STOKRE_1
  description: SUPPLY_B_PUMP_STOKRE_1
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2023-04-13T11:02:45.2713639+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 67
  address: 55
  use: true
  gui_display: true
  name: SUPPLY_B_PUMP_STOKRE_2
  description: SUPPLY_B_PUMP_STOKRE_2
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2023-04-13T11:02:45.2713639+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 68
  address: 68
  use: false
  gui_display: false
  name: SPARE_68
  description: SPARE_68
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2023-04-13T11:02:45.2713639+09:00
  dt_on: 0001-01-01T00:00:00.0000000
- no: 69
  address: 69
  use: false
  gui_display: false
  name: SPARE_69
  description: SPARE_69
  etc: 
  unit: N.O
  value: false
  value_raw: false
  dt_off: 2023-04-13T11:02:45.2713639+09:00
  dt_on: 0001-01-01T00:00:00.0000000
