total_cnt: 20
fifo_max_minute: 60
trend_data:
- name: SUPPLY_TEMP_A
  use: true
  value: 3.9820000000000002
  type: SUPPLY_TEMP_A
- name: SUPPLY_TEMP_B
  use: true
  value: 13.385999999999999
  type: SUPPLY_TEMP_B
- name: SUPPLY_HEATER_A
  use: false
  value: 24.727
  type: SUPPLY_HEATER_A
- name: SUPPLY_HEATER_B
  use: false
  value: 33.700000000000003
  type: SUPPLY_HEATER_B
- name: TANK_TEMP_A
  use: true
  value: 44.372999999999998
  type: TANK_TEMP_A
- name: TANK_TEMP_B
  use: true
  value: 52.197000000000003
  type: TANK_TEMP_B
- name: CIRCULATION_HEATER_1
  use: false
  value: 62.981000000000002
  type: CIRCULATION_HEATER_1
- name: CIRCULATION_HEATER_2
  use: false
  value: 73.722999999999999
  type: CIRCULATION_HEATER_2
- name: CIRCULATION_TEMP
  use: true
  value: 84.861000000000004
  type: CIRCULATION_TEMP
- name: TS_09
  use: true
  value: 94.855000000000004
  type: TS_09
- name: THERMOSTAT_SUPPLY_A
  use: false
  value: 102.535
  type: THERMOSTAT_SUPPLY_A
- name: THERMOSTAT_SUPPLY_B
  use: false
  value: 112.05799999999999
  type: THERMOSTAT_SUPPLY_B
- name: THERMOSTAT_CIRCULATION
  use: false
  value: 123.807
  type: THERMOSTAT_CIRCULATION
- name: Temp13
  use: false
  value: 134.715
  type: NONE
- name: Temp14
  use: false
  value: 142.356
  type: NONE
- name: Temp15
  use: false
  value: 154.155
  type: NONE
- name: Temp16
  use: false
  value: 162.45699999999999
  type: NONE
- name: Temp17
  use: false
  value: 172.08099999999999
  type: NONE
- name: Temp18
  use: false
  value: 184.172
  type: NONE
- name: Temp19
  use: false
  value: 192.04900000000001
  type: NONE
- name: Temp20
  use: false
  value: 192.04900000000001
  type: NONE