path:
  yaml: C:\Program Files\AK\CDS\Config\Yaml\
db_target:
- ip: 127.0.0.1
  port: 3306
  driver: MariaDB ODBC 3.1 Driver
  database: ctc
  id: root
  password: 1234
  connection: DRIVER={MariaDB ODBC 3.1 Driver};SERVER=192.168.0.110;PORT=3306;USER=root;PASSWORD=express2345;DATABASE=ctc;
- ip: 127.0.0.1
  port: 3306
  driver: MariaDB ODBC 3.1 Driver
  database: cds
  id: root
  password: 1234
  connection: DRIVER={MariaDB ODBC 3.1 Driver};SERVER=192.168.0.110;PORT=3306;USER=root;PASSWORD=express2345;DATABASE=cds;
- ip: 127.0.0.1
  port: 3306
  driver: MariaDB ODBC 3.1 Driver
  database: fdc
  id: root
  password: 1234
  connection: DRIVER={MariaDB ODBC 3.1 Driver};SERVER=192.168.0.110;PORT=3306;USER=root;PASSWORD=express2345;DATABASE=fdc;
